version: '3'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/helpdesk
      - JWT_SECRET=change-me
      - STUB_MODE=true
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
